# Generated by Django 4.1.4 on 2023-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=50)),
                ('cmp_email', models.EmailField(max_length=254)),
                ('tille', models.CharField(max_length=100)),
                ('jobtype', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=25)),
                ('wrktype', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('exp_required', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('qualification', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='regismodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
