# Generated by Django 4.1.4 on 2023-01-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodels',
            old_name='tille',
            new_name='title',
        ),
    ]
